### ISSUE TITLE
[Code] Add additional services for MWDI-1.0.0 for ALA app

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#147]
Additional services need to be added:
```
        - operation-name: /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol={local-id}/vlan-interface-1-0:vlan-interface-pac/vlan-interface-configuration
          uuid: mwdi-1-0-0-op-s-is-106

        - operation-name: /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol={local-id}/wire-interface-2-0:wire-interface-pac/wire-interface-status
          uuid: mwdi-1-0-0-op-s-is-202
```

**Comment by kmohr-soprasteria** [comment]
neu hinzufügen:
node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/equipment={uuid}?fields=name;actual-equipment(manufactured-thing(equipment-type;equipment-instance))

**Comment by kmohr-soprasteria** [comment]
3. request ist falsch: es ist im vlan-interface-configuration nicht capability!

```
https://10.20.64.13:8443/rests/data/network-topology:network-topology/topology=topology-netconf/node=325255282/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point=VI-1/layer-protocol=1/vlan-interface-1-0:vlan-interface-pac/vlan-interface-configuration/interface-kind
```

**Comment by anacabbar** [comment]
Hallo Katharina, ich habe eben mitbekommen, die folgende services sind auch notwendig. Damit ist die Service Liste für den ersten Release des ALAP fertig. 
4.
- operation-name: /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol={local-id}/wire-interface-2-0:wire-interface-pac/wire-interface-status/interface-status
   uuid: alap-1-0-0-op-c-is-mwdi-1-0-0-013
5.
  - operation-name: /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}?fields=client-ltp
   uuid: alap-1-0-0-op-c-is-mwdi-1-0-0-014

**Comment by kmohr-soprasteria** [comment]
Im MWDI muss der Filter nicht berücksichtigt werden, sondern nur der Ressource-Name vor dem Filter, damit ergeben sich folgende 4 Paths:

/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}

/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/equipment={uuid}

/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol={local-id}/vlan-interface-1-0:vlan-interface-pac/vlan-interface-configuration/interface-kind

/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol={local-id}/wire-interface-2-0:wire-interface-pac/wire-interface-status/interface-status

**Comment by anacabbar** [comment]
(3) und (4) wurden korrigiert auf der Service Liste des ALAP
