### ISSUE TITLE
Create ServiceList

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MicroWaveDeviceInventory#17]
- [x] Read [Creating the ServiceList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/CreatingServiceList/CreatingServiceList.md)
- [x] Create an issue for writing the ServiceList and put your first thoughts about the required services into it.
- [x] Create a local feature branch from this issue in your VisualStudioCode installation
- [x] Write the ServiceList in your local feature branch
- [x] Check your result against the provided documentation
- [x] Create a Pull-Request from your local feature branch into the develop branch; configure Katharina to be Reviewer; assign the Pull-Request to OpenBackhaul
- [x] Respond to feedback to the Pull-Request and consolidate the findings
- [x] Delete your local feature branch after successfully merging into develop
- [x] Close this issue

**Comment by xiidoz** [comment]
I'd like to collaborate, please.
