### ISSUE TITLE
Create ProfileInstanceList

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MicroWaveDeviceInventory#19]
- [x] Read [Creating the ProfileInstanceList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/CreatingProfileInstanceList/CreatingProfileInstanceList.md)
- [x] Create an issue for writing the ProfileInstanceList and put your first thoughts about the required instances of Profiles into it.
- [x] Create a local feature branch from this issue in your VisualStudioCode installation
- [x] Write the ProfileInstanceList in your local feature branch
- [x] Check your result against the provided documentation
- [x] Create a Pull-Request from your local feature branch into the develop branch; configure Katharina to be Reviewer; assign the Pull-Request to OpenBackhaul
- [x] Respond to feedback to the Pull-Request and consolidate the findings
- [x] Delete your local feature branch after successfully merging into develop
- [x] Close this issue

**Comment by kmohr-soprasteria** [comment]
- file has been updated from repo template, uuids have been modified for mwdi app & added padding at the end to have the same length for all uuids.
- added some example stringProfileInstances; actually required profileInstances need to be identified first. Therefore, only a commit, but no pull request issued, yet.
