### ISSUE TITLE
[Concept] Filtering information and future support

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#200]
The MWDI will allow for filtering of ressources:
- content-filter: not supported (config / nonconfig)
- fields-filter: supported, follows RFC 8040
  - discussion see [issue #64](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/64)
  - open point: Iswaryaa will come up with a pattern for the syntax description which can be added to the OAS, see [issue 119](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/119)
- improved fields-filter: possibly supported in later versions
  -  Thorsten wanted an extension to the regular fields filter: it should be possible to add actual values into the filter and then only results where the values match should be returned.

**Comment by openBackhaul** [comment]
This issue has been rephrased in Issue #496. 
Issue #496 has been rated as a potential for performance improvements in future.
This issue will be closed. 
Issue #496 will be schedule for some release after putting MWDI 1.0.1_impl into operation and collecting experience.
