### ISSUE TITLE
[Code] Description in IntegerProfile (later MWDI release)

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#245]
After switching on an updated ApplicationPattern that implements an updated IntegerProfile with an additional description field (see [ApplicationPattern issue # 795](https://github.com/openBackhaul/ApplicationPattern/issues/795)), the comments in the instances of IntegerProfile in the ProfileInstanceList shall be transferred into real attributes.

This change affects:
- ProfileList
  - profile-name: 'IntegerProfile'
    uuid: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-integer-p-[0-9]{3}$'
    capability:
      integer-name: string
      **description: string**
      unit: string
      minimum: integer
      maximum: integer
    configuration:
      integer-value: integer
- ProfileInstanceList
- CONFIGfile
- OAS
  - ControlConstruct
  - ProfileCollection
  - additional resource paths towards description attribute in the OAM section

see also https://github.com/openBackhaul/MacAddressTableRecorder/issues/50

Update: the field now is included with name "purpose"

**Comment by openBackhaul** [comment]
To be checked, whether [ApplicationPattern issue # 795](https://github.com/openBackhaul/ApplicationPattern/issues/795) has been completed.
