### ISSUE TITLE
Update diagrams according to latest NotificationProxy updates

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#323]
Proposed solution:
In all relevant diagrams update all relevant _objectRefId_ with _resource_ attribute

Problem description:
- The NotificationProxy receives the objectRefId when it receives notifications from the Controller or devices
- the NP specification has been changed to not deliver the *objectRefId* to its subscribers but the *resource* instead
- the MWDI diagrams do not yet reflect this change
- see diagrams 021-026
- possibly also changes inside the diagrams related to notification sent out by the MWDI changes may be necessary (120-122) (depends on the callbacks)
- comparison between callbacks from NP and MWDI are necessary

**Comment by openBackhaul** [comment]
The format of the notifications sent by the NotificationProxy does no longer contain the objectRefId that is sent by the device.
The objectRefId gets replaced by the resource attribute.
All diagrams and lists have been corrected accordingly.
