### ISSUE TITLE
Security on callbacks towards ODL

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MicroWaveDeviceInventory#330]
The ODL will be closed for unauthorized access, so connection approval can be enforced via the operation key management at the MWDI.

=> All callbacks towards ODL need to support a security method.

It is to be clarified whether 
- basicAuth (requires an OperationClient supporting it and a method for storing the ODL authentication code) or
- apiKeyAuth (not sure, whether ODL is supporting it)
shall be applied.

**Comment by kmohr-soprasteria** [comment]
BasicAuth will be used
