### ISSUE TITLE
[To investigate] content filter to manage mediator behaviour

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MicroWaveDeviceInventory#341]
It might be necessary to manage the behavior of one of the mediators by applying the content filter.
Further investigation required.

**Comment by kmohr-soprasteria** [comment]
What exactly should be investigated here? what behaviour exactly should be managed? for which mediator?

**Comment by openBackhaul** [comment]
The concept of the issue is unclear.
Issue will be closed.
