### ISSUE TITLE
Path parameters with "-" character (i.e. mount-name) to be changed

### ISSUE THREAD

**Issue by nardecchia-siae** [openBackhaul/MicroWaveDeviceInventory#457]
For all the callbacks with parameters in the path containing the hyphen (for example mount-name or local-id), when the api is called both via swagger or postman a 404 not found response is received.

Debugging the code the controllers are not called at all as they seems to be not recognized at all by the framework.

Fixed manually removing the hyphen and changing the parameter name in lower camel case.

**Comment by kmohr-soprasteria** [comment]
Solution:
we will change the path-parameters in all here and in all future specifications to be in lower camel case.

**Comment by openBackhaul** [comment]
Moved to milestone 1.1.0_spec as there is a lot of new code prepared that suffers from the same problem.

**Comment by kmohr-soprasteria** [comment]
Discussed today in AppOwner meeting that the hyphen normally should not cause any problems. Therefore asked TechM for some feedback on it. Prathiba answered:

> In the server side implementation, we are using a package called OAS3tool that validates the API’s syntax.
> By default , this OAS3tool package don’t have the capability to consider the path parameter with a hyphen.
> 
> Either, 
> •	the {mount-name}, {local-id} in the OAS specification shall be modified to {mountName}, {localId}
> (or) 
> •	we need to try extending the OAStool to see the possibility to support hypen in the path parameter
> 
> Note :  This problem will happen only in the serving application(where the paths are defined) and not in the consuming applications(where the paths are used in the callbacks).

Next step: discuss whether we first try to extend the OAStool

**Comment by openBackhaul** [comment]
As a parameter, mount-name and local-id have been replaced by mountName and localID.
