### ISSUE TITLE
Modify method name for Get ltp Augment and Get Logical Termination Point

### ISSUE THREAD

**Issue by nardecchia-siae** [openBackhaul/MicroWaveDeviceInventory#466]
There is a mistake in the naming of get methods for api's:

- **/core-model-1-4:network-control-domain=live/control-construct={mount-name}/logical-termination-point={uuid}**
- **/core-model-1-4:network-control-domain=live/control-construct={mount-name}/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac**

In particular from OpenApi.yaml file:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/142794948/391401f0-0b2b-46e5-8a99-47518438f3cc)
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/142794948/70acada4-ad41-48a2-80c2-425cfcad0497)

![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/142794948/9787e42b-56b8-4359-b8a6-1402ab752dd5)
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/142794948/68b4e9ee-c0e9-4e9b-8949-cd47bd2e65d8)

There is also a duplication in MicroWaveDeviceInventory.yaml file at line 7610:
<img width="398" alt="image" src="https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/142794948/faf6fdda-4a5b-43e4-b439-392096b606eb">

To go ahead with development I have changed the name of the methods and removed the duplication.

**Comment by openBackhaul** [comment]
Changed as proposed.
