### ISSUE TITLE
[Info] What to do when no answer comes from ODL getting the Devicelist

### ISSUE THREAD

**Issue by zaia-siae** [openBackhaul/MicroWaveDeviceInventory#467]
When the app doesn't get any answer from ODL about the new device list, the app could reiterate the request as many times as specified inside the load.json configuration file (either adding a new field or using maximumNumberOfRetries already used for the device control construct). 
Expired the retries:
(1) - the app could keep going on with the current devicelist 
(2) - the app could stop if there is not any device list stored in elasticsearch (app just started for the first time)

**Comment by openBackhaul** [comment]
The MWDI shall attempt to read the device status list at the controller for the maximumNumberOfRetries times.
If not successful, it shall be assumed that the controller and all connected devices are not available and the cache shall be purged.

**Comment by kmohr-soprasteria** [comment]
can we close the issue now? has this been implemented?
