### ISSUE TITLE
Fields filtering without url encoding

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#510]
Currently the fields filter is only working if it is url encoded.
We definitely need the fields filter to work WITHOUT url encoding.

not working:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/3901ea09-7af0-4754-8489-615417491216)
working:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/656fece4-3de2-4345-975e-2431f029f722)

**Comment by nardecchia-siae** [comment]
I've tried to check why it is required that the fields parameter must be url encoded but I found that the request never arrives at the controllers.
Some library components maybe tries to validate the url and refuses it if it's not in the format required by the validator.

I'm continuing investigating the issue but it seems to be not related to our implementation of individual services.

**Comment by kmohr-soprasteria** [comment]
asked SIAE to fix this asap, as other apps should not have to implement url encoding on their side, when addressing the MWDI

**Comment by nardecchia-siae** [comment]
I confirm that the requests never arrives to our controller.
They are parsed before by a validator implemented in the framework which filters the filter "fields" without url encoding.

**Comment by kmohr-soprasteria** [comment]
Info from Prathiba:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/4fec4cce-c0ca-4586-91bf-d5b27af45987)

complete mail with attachments:
[Regarding url encoding.zip](https://github.com/openBackhaul/MicroWaveDeviceInventory/files/14359189/Regarding.url.encoding.zip)
