### ISSUE TITLE
Only path parameters to be in upperCamelCase

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#549]
- When mount-name is a path parameter it will be in upperCamelCase
- in schemas the "-" shall remain, this applies to requestBodies and responses

e.g. see (wrong) naming in response:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/2dfc53e6-864d-4d19-827d-3485cfbaa11b)
naming in related schema:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/dae19e8a-4b09-4492-863e-a0b4157a8da2)

**Comment by kmohr-soprasteria** [comment]
Another example found by Jan:
/v1/provide-list-of-device-interfaces has the "mount-name" in the requestBody:
![MWDI_OpenAPI](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/e25fc7d9-f0d0-4322-a124-0a7cb0737b5c)

However, when "mount-name" is used in the requestBody an issue is shown:
![FehlerNachricht](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/27ed111a-cf2b-4aa2-b3e3-bf0c0d3fe101)

It works only with "mountName":
![Corret_Request](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/89a61a82-8455-4ad5-aff8-4ee23837fc21)

**Comment by nardecchia-siae** [comment]
Closed with #751
