### ISSUE TITLE
[Reporting] Request to include logging mechanism for requests of retrieving the CC data from Controller devices and storing it in the cache 

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/MicroWaveDeviceInventory#617]
> **Background of the issue creation :** 
> After the deployment of MWDI application in pilot environment , when andreas lattoch and testing team where analyzing the performance of the controller , team was unable to trace the requests sent  and responses received to and from the controller.

**Problem Description:** 

Once we deploy the MWDI application in pilot environment , we retrieve CC's of nearly 40k devices and store in the cache of MWDI application . During this cyclic process sliding window concept will update the CC . In the console window we are able to see the prgress of  this sliding window in a high level but could not able to figure out whether controller is able to recieve the requests and able to respond to the request sucessfully or not as there is no detailed logging mechanism present. 

If a logging mechanism is included with details of the request and response(like response-code), while retrieving the CC data from controller devices and storing it in the cache of MWDI application, this would be useful for tracing the requests sent and the response received (in case of any error).

**Comment by zaia-siae** [comment]
The procedure deployed so far, prints a lot of information, it's very verbose especially when we deal with a large device list and sliding window. We can keep the current setup and add the status info of the answer or refact the logging structure, reducing the number of rows printed and correlating request and response. This solution can help user to follow the process with more clarity, without losing in very long device list and sliding window log rows.
Following a sample of logging for different response status:

******************************************************
                  MWDI Application started

Device List length: 35213
Sliding Window length: 500

Waiting for responses from controller....
******************************************************

------------------------------------------------------
Device ID: 34768900
Queued Time: 19:30.44
Response Time: 19:32:26
Delta Time: 102s
Response: OK 
------------------------------------------------------
Device ID: 85380023
Queued Time: 19:30.45
Response Time: 19:32:44
Delta Time: 119s
Response: Error (code xyz)
------------------------------------------------------
Device ID: 23980102
Queued Time: 19:30.46
Response Time: 19:55:44
Delta Time: 1508s
Response: Timeout 
------------------------------------------------------

Let us know if this proposal is ok

**Comment by zaia-siae** [comment]
Now, only info very useful are logged.
