### ISSUE TITLE
Response-code of the API shall contain actual response code in case of negative responses

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/MicroWaveDeviceInventory#618]
While receiving a errored response , instead of actual errored response (eg.,, 400, 404, 503) in response-code of the response, the response-code is 200 and the response-data contains the actual error status and message. 

In the below example, the status is expected to be "404", but it is present inside response-data and the data shall expected to contain the error message. 

Example:
```
{status: 200, statusText: 'OK', headers: {…}, config: {…}, request: ClientRequest, …}
config:
{url: 'http://172.28.127.18:3008/core-model-1-4:netwo…ace-2-0:air-interface-pac/air-interface-status', method: 'get', data: '{}', headers: {…}, params: {…}, …}
data:
{code: 404, message: 'Not Found'}
status:
200
statusText:
'OK'
```

**Comment by PrathibaJee** [comment]
Decision on 17th of November 2023 in MW SDN Implementation and Integration Feedback:
The requested functionality is not required as the MWDI response body incase of described usecase is as expected.
Please close this issue. Many thanks.

**Comment by nardecchia-siae** [comment]
Close this issue as requested
