### ISSUE TITLE
Device is not removed from cache when device connection-status is changed from connected to connecting 

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#780]
When controller attribute value change notification is sent by Notification proxy application, MWDI is not accepting notification on API:/v1/regard-controller-attribute-value-change and that node is not removed from the cache database application. 

When same notification is tried on swagger API:/v1/regard-controller-attribute-value-change, observing "TypeError: Failed to fetch"
Verison:test_v1.0.7
Notification used in swagger:
```
{
"notification-proxy-1-0:attribute-value-changed-notification":{
"counter":1,
"timestamp":"2023-12-14T14:40:28.749419167Z",
"resource":"/core-model-1-4:network-control-domain=live/control-construct=OpenDayLight1/logical-termination-point=513559991A/layer-protocol=0/mount-point-1-0:mount-point-pac/mount-point-configuration","attribute-name":"connection-status",
"new-value":"connecting"
}
}
```

**Comment by nardecchia-siae** [comment]
Just a question to be sure that the current implementation is correct.
The resource field in the body of notification message is correct as reported in the current issue?
I mean, the Control construct of the node to remove is written in the Logical-termination-point field of the resource?

**Comment by Ziabatcha** [comment]
Still observing the same issue in tag:test_v1.1.0
