### ISSUE TITLE
Create ForwardingList

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MicroWaveDeviceInventory#80]
- [x] Read [Creating the _ForwardingList_](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/CreatingForwardingList/CreatingForwardingList.md)
- [x] Create an _Issue_ for writing the _ForwardingList_ and put your first thoughts about relationships between events and reactions into it.
- [x] Create a local feature branch from this _Issue_ in your VisualStudioCode installation
- [x] Elaborate the _ForwardingList_ in your local feature branch
- [x] Check your result against the provided documentation
- [ ] Create a _Pull-Request_; appoint a team member to be _Reviewer_; assign the _Pull-Request_ to yourself
- [ ] Respond to the feedback to the _Pull-Request_ and fix the findings
- [ ] _Merge_ into _develop_ branch; delete remote feature branch; assure the _Issue_ being closed
- [ ] Delete your local feature branch
- [ ] Close this _Issue_

**Comment by kmohr-soprasteria** [comment]
initially added services for bequeath-your-data-and-die, but as a database is used, data handover will be done as database handover instead.

**Comment by kmohr-soprasteria** [comment]
[Concepts of the ForwardingList.pdf](https://github.com/openBackhaul/MicroWaveDeviceInventory/files/11404394/Concepts.of.the.ForwardingList.pdf)
