### ISSUE TITLE
Required attributes for /v1/regard-device-object-creation

### ISSUE THREAD

**Issue by nardecchia-siae** [openBackhaul/MicroWaveDeviceInventory#833]
There is a mismatch in required attributes between Notification Proxy and MWDI for the device object creation notification api.

In notification proxy yaml, for object creation below are the attributes required to the subscriber sending information.

NP:
required:
  - counter
  - timestamp
  - object-path

 

But MWDI yaml spec is having extra attribute “object-type” for API:/v1/regard-device-object-creation.

Because of this, validation of object creation notification is getting failed.

MWDI:
required:
  - counter
  - timestamp
  - object-path
  - object-type

**Comment by openBackhaul** [comment]
Please, be invited to implement according to your preference (with or without object-type attribute) and document your decision here, so we can rectify the specification.

**Comment by nardecchia-siae** [comment]
The object-type attribute can be removed as required object from specification as it is not used in the implementation of the related api.

**Comment by kmohr-soprasteria** [comment]
Removed the object-type from list of required attributes; kept it as optional attribute.

**Comment by openBackhaul** [comment]
Stringently removed the object-type attribute from all ObjectCreationNotifications.
