### ISSUE TITLE
Typo in specification of some api

### ISSUE THREAD

**Issue by nardecchia-siae** [openBackhaul/MicroWaveDeviceInventory#834]
There is a typo in the latest specification for the following api's:

* /core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct{uuid1}

* /core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct{uuid1}/fc-port{localId}

In the first url there should be a "=" between **forwarding-construct** and **{uuid1}** and in the second between  **forwarding-construct** and **{uuid1}** and also between  **fc-port** and **{localId}**

Same issue also in cache api's

**Comment by openBackhaul** [comment]
Yes, I confirm these two (three) mistakes. 
If you would wish you could already correct the implementation.

The following  "=" symbols are missing in path statements:
```diff
-/core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct{uuid1}
+/core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct={uuid1}

-/core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct{uuid1}/fc-port{localId}
+/core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct={uuid1}/fc-port={localId}
```

CTRL+h to be used for correcting the paths in:
- ServiceList
- ForwardingList
- CONFIGfile
- OAS

**Comment by openBackhaul** [comment]
Massimo indicated in a separate email that the cache paths are affected, too.
I confirm also these two (three) mistakes. 
According to my understanding they will already be corrected in the release that is currently under implementation.

The following  "=" symbols are missing in path statements:
```diff
-/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct{uuid1}
+/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct={uuid1}

-/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct{uuid1}/fc-port{localId}
+/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/forwarding-construct={uuid1}/fc-port={localId}
```

CTRL+h to be used for correcting the paths in:
- ServiceList
- ForwardingList
- CONFIGfile
- OAS

**Comment by openBackhaul** [comment]
Added "=" in cache paths and a couple of additional occurrences.
