### ISSUE TITLE
Forwarding construct attribute has to be changed

### ISSUE THREAD

**Issue by nardecchia-siae** [openBackhaul/MicroWaveDeviceInventory#843]
In the control-construct, the forwarding-domain attribute contains the forwarding construct that as per the core-model definition should be named as "fc" while in the yaml file is reported as "forwarding-construct".

Please correct the yaml file with the correct naming.

Also the following APIs should be fixed with the correct naming:

* /core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/**_forwarding-construct_**={uuid1}
* /core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/**_forwarding-construct_**={uuid1}/fc-port={localId}
* /core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/**_forwarding-construct_**={uuid1}
* /core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/**_forwarding-construct_**={uuid1}/fc-port={localId}

**Comment by kmohr-soprasteria** [comment]
Note: the change from forwarding-construct to fc needs not to be done for the default forwarding-domain schema under components, but only for the schema which is related to the MWDI/device CC definition (i.e. in the `FORWARDING_DOMAIN` schema only)
