### ISSUE TITLE
Observing 401 unauthorized error, as default operation-key of MWDIv1.1.3 differs from other applications operation-key

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#868]
Currently MWDIv1.1.3 is deployed with new operation-key: "n.a." but other applications which are dependent with MWDI uses default operation-key : "Operation key not yet provided."
Because of this difference in operation-key, all other applications API requests towards MWDI is getting failed with 401 unauthorized.

Kindly suggest, whether MWDI have to use old operation-key or other dependent applications have to use new operation-key:”n.a.” to access MWDI APIs.

**Comment by kmohr-soprasteria** [comment]
- intermediate solution: change the CONFIGfile in use, just CTRL+h “n.a.” by “Operation key not yet provided.”
- with #862 a permanent solution will be applied

**Comment by Ziabatcha** [comment]
Tested okay with test_v1.1.4.
Load.json reflects the op-key as 'operation ket not yet provided."
