### ISSUE TITLE
Observing  401 unauthorised error - cache/live fc and fc-port

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#869]
TAG: v1.1.3

Observing  401 unauthorised error for  CACHE API 

/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/fc={uuid1}

/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/fc={uuid1}/fc-port={localId}

The API differs between LOAD.JSON and YAML file.

In swagger its reflected as FC and in YAML its reflected as forwarding-construct.

```
/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/fc={uuid1}
{
  "code": 401,
  "message": "unauthorized",
  "errors": [
    {
      "path": "/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/fc={uuid1}",
      "message": "unauthorized"
    }
  ]
}
```

```

curl -X GET "http://xx:xx/core-model-1-4:network-control-domain=cache/control-construct=513250004/forwarding-domain=FD-VLAN-1234-1/fc=FC-1234-1-3392/fc-port=FCPort-1234-1-3392" -H "accept: application/json" -H "user: User Name" -H "originator: Resolver" -H "x-correlator: 550e8400-e29b-11d4-a716-446655440000" -H "trace-indicator: 1.3.1" -H "customer-journey: Unknown value" -H "operation-key: Operation key not yet provided."


http://xx:xx/core-model-1-4:network-control-domain=cache/control-construct=513250004/forwarding-domain=FD-VLAN-1234-1/fc=FC-1234-1-3392/fc-port=FCPort-1234-1-3392


{
  "code": 401,
  "message": "unauthorized",
  "errors": [
    {
      "path": "/core-model-1-4:network-control-domain=cache/control-construct={mountName}/forwarding-domain={uuid}/fc={uuid1}/fc-port={localId}",
      "message": "unauthorized"
    }
  ]
}

```

**Comment by Ziabatcha** [comment]
Issue observed with fc and fc-port LIVE API in  build v1.1.3

http://xx:xx/core-model-1-4:network-control-domain=live/control-construct=513250004/forwarding-domain=FD-VLAN-1234-1/fc=FC-1234-1-3392

http://xx:xx/core-model-1-4:network-control-domain=live/control-construct=513250004/forwarding-domain=FD-VLAN-1234-1/fc=FC-1234-1-3392/fc-port=FCPort-1234-1-3392

{
"code": 401,
"message": "unauthorized",
"errors": [
{
"path": "/core-model-1-4:network-control-domain=live/control-construct={mountName}/forwarding-domain={uuid}/fc={uuid1}/fc-port={localId}",
"message": "unauthorized"
}
]
}

**Comment by nardecchia-siae** [comment]
I think that the issue is not an issue.
Unauthorized means that the operation key is not correct.
Infact in my environment in load.json file the operation key is "n.a." and both live and cache api's are working only using that operation key.
Any other key is rejected with the message reported in the bug.

**Comment by Ziabatcha** [comment]
Tested okay with test_v1.1.4
Able to get response for both fc and fc-port API from CACHE/LIVE.
