### ISSUE TITLE
[NotificationService] Observing 404 error when notification received on API:/v1/regard-device-object-creation

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#875]
When Object creation notification is received on API:/v1/regard-device-object-creation, observing error 404 in MWDI.

Tag:test_1.1.3

```
{"notification-proxy-1-0:object-creation-notification":{"counter":1,"timestamp":"2024-03-05T09:23:35.0+00:00","object-path":"/core-model-1-4:network-control-domain=live/control-construct=513250006/forwarding-domain=VLAN-FD/fc=VLAN-2801"}}
```

**Comment by nardecchia-siae** [comment]
Tested with the following call

```
curl -X POST "http://localhost:8080/v1/regard-device-object-creation" -H "accept: application/json" -H "user: User Name" -H "originator: Resolver" -H "x-correlator: 550e8400-e29b-11d4-a716-446655440000" -H "trace-indicator: 1.3.1" -H "customer-journey: Unknown value" -H "operation-key: Operation key not yet provided." -H "Content-Type: application/json" -d "{\"notification-proxy-1-0:object-creation-notification\":{\"counter\":1,\"timestamp\":\"2024-03-05T09:23:35.0+00:00\",\"object-path\":\"/core-model-1-4:network-control-domain=live/control-construct=513250006/forwarding-domain=VLAN-FD/fc=VLAN-4001\"}}"
```

**Comment by Ziabatcha** [comment]
Issue still observed with test_1.1.4

**Comment by Ziabatcha** [comment]
Still observing this issue in 1.1.2.f_impl package.
Logs:
[12.07.2024 08:42.23.589] [LOG]   Send data to Requestor:http://172.28.127.10:3008/core-model-1-4:network-control-domain=live/control-construct=513250007/forwarding-domain=VLAN-FD/fc=VLAN-1004
[12.07.2024 08:42.24.232] [LOG]
 callback : http://172.28.127.19:8181/rests/data/network-topology:network-topology/topology=topology-netconf/node=513250007/yang-ext:mount/core-model-1-4:control-construct/forwarding-domain=VLAN-FD/fc=VLAN-1004 header :{"Authorization":"Basic YWRtaW46YWRtaW4="}body :""response code:200
[12.07.2024 08:42.24.244] [ERROR] NotFoundError: Field "fc"="513250007+VLAN-1004" not found in cache
    at Object.exports.cacheUpdateBuilder (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/cacheUpdateBuilder.js:53:17)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:6784:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
GET /core-model-1-4:network-control-domain=live/control-construct=513250007/forwarding-domain=VLAN-FD/fc=VLAN-1004 200 661.347 ms - 1219
POST /v1/regard-device-object-creation 204 702.137 ms - -

**Comment by kmohr-soprasteria** [comment]
also see #1001: when I try to create or delete an object through the related regard-services, MWDI returns a "409, conflict".

**Comment by Ziabatcha** [comment]
Tested with latest  MWDI version 1.1.2.g_impl, Issue is no longer observed. 

Object Creation :

````
http://XXXXX:XXXX/v1/regard-device-object-deletion
 
{"notification-proxy-1-0:object-deletion-notification":{"counter":1,"timestamp":"2024-10-14T07:17:22.0+00:00","object-path":"/core-model-1-4:network-control-domain=live/control-construct=513250009/forwarding-domain=VLAN-FD/fc=VLAN-3387"}}
 `````
Response : 204 OK
