### ISSUE TITLE
[?] Bequeath Your Data And Die

### ISSUE THREAD

**Issue by zaia-siae** [openBackhaul/MicroWaveDeviceInventory#882]

**Comment by kmohr-soprasteria** [comment]
what's this issue about?

**Comment by zaia-siae** [comment]
It's a functionality for transferring all existing subscriptions of 3rd applications from current version (Old Release)  to the new one (New Release). Once the transferring is complete the Old Release is deactivate and the new one is started

**Comment by kmohr-soprasteria** [comment]
can this be closed?
