### ISSUE TITLE
[ConvenienceServices] Error responses inconsistent

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#886]
The error responses are inconsistent; 
if an unknown link-id/device-name is passed in the requestBody:
1. /v1/provide-list-of-parallel-links: returns 500 (pic1)
2. /v1/provide-list-of-device-interfaces: return code is 200, but code in the message is 404 (pic2)
3. /v1/provide-list-of-actual-device-equipment (pic3)

The responseCodes are not aligned between both services and for (2, 3) the responseCode does not match the code given in the responseBody.

For cache services I see 500, "unable to fetch records..." which is aligned across the cache responses I checked, but again not aligned with services above (pic4/5).

We anyway should align error responses across the various applications, but still it should be at least aligned across services in a single application.

| Pic | Example                                                                                                                 |
|-----|-------------------------------------------------------------------------------------------------------------------------|
| 1   | ![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/0562513c-d24d-4aec-8983-4fc73c367ff0) |
| 2   | ![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/6067eb88-ba56-4748-86a5-9bb704d67722) |
| 3   | ![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/4a407618-3360-4df0-9ada-61a81613b669) |
| 4   | ![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/cc61f8f8-f1b3-4d8e-888e-03d1a189bb95) |
| 5   | ![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/ea8d83e6-a2ac-47c3-9817-a60d9871653c) |

**Comment by nardecchia-siae** [comment]
To be tested in tag test_v1_1_4

**Comment by kmohr-soprasteria** [comment]
This can be closed, if the error response is consistently 4xx.

(note that with v1.2.1 the error codes will be aligned as described in #997, to new error codes 460/461.)

**Comment by kmohr-soprasteria** [comment]
tested with 1.1.2g_impl. 
all 3 services returned 404. issue is closed.
