### ISSUE TITLE
Observing 500 internal-server-error when user tried to create link-port 

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#900]
User tried to create new link port after link creation with min-of-rest data, Observing 500 internal server error 

```
url:
/core-model-1-4:network-control-domain=cache/link=link006007/link-port=1


Body:
{
  "core-model-1-4:link-port": [
    {
      "local-id": "1",
      "link-port-direction": "core-model-1-4:PORT_DIRECTION_INPUT",
      "logical-termination-point": "513250006+LTP-MWPS-TTP-ODU-A"
    }
  ]
}
```

**Comment by Ziabatcha** [comment]
If we are using above template, is two different UUID will get created (i.e. one uuid for min-of-rest and another uuid for generic). Is this expected ? then which UUID we will give in POST-/v1/provide-list-of-parallel-links

**Comment by kmohr-soprasteria** [comment]
I clarified this with Thorsten and created issue #911 with an explanation on generic and minimum for rest sub-schemas.
- /v1/provide-list-of-parallel links uses the _minimum for rest_ definition, which is to be used for AirInterface links
- generic schema is for future use (for non AirInterface links, i.e. this will have different uuids/linkIds)

So in summary: a link should be only created according to either one of the definitions, but not with both at once.
For testing the link-port service, it would suffice to write a testLink to the cache following the generic definition with some sample linkId.

**Comment by Ziabatcha** [comment]
As per the discussion, Link-port creation will be applicable for non-air-interface port.  Current version is not supported for non-air-interface port.
