### ISSUE TITLE
Unsupported vlan-interface-current-performance LIVE API to be removed from MWDI .

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#908]
Unsupported vlan-interface-current-performance API to be removed from MWDI live.
```
/core-model-1-4:network-control-domain=live/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/vlan-interface-1-0:vlan-interface-pac/vlan-interface-current-performance
```
When tried to execute the API its throwing 409 conflict error

**Comment by Ziabatcha** [comment]
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/150062735/da970182-5171-4d7d-ad84-030f4ce7a847)

```
http://xxx:xxx/core-model-1-4:network-control-domain=live/control-construct=513250010/logical-termination-point=VI-10/layer-protocol=10/vlan-interface-1-0:vlan-interface-pac/vlan-interface-current-performance
Error:
{
  "code": 409,
  "message": "Conflict"
}

```

**Comment by Ziabatcha** [comment]
As per the YANG , vlan-interface-current-performance attribute is not supported.
But in MWDI , LIVE we are able to see the API for vlan-interface-current-performance . Please remove it from swagger.

![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/150062735/b403eb49-c75b-4866-a831-2910219c6f14)

**Comment by kmohr-soprasteria** [comment]
API entries have been removed from spec (see #913)

**Comment by Ziabatcha** [comment]
Tested with MWDI latest version test_v1.1.5.
Issue is no longer observed. vlan-interface-current-performance ( domain=live)  API removed from swagger

![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/150062735/3dfa93be-3084-4889-a196-2eb2409cff43)

**Comment by Ziabatcha** [comment]
Tested OKAY with MWDI latest version test_v1.1.5.
