### ISSUE TITLE
[Clarification] Create concept of services for self-mgmt

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#91]
Nach AppOwner-Meeting heute hat sich rausgestellt, dass das Management nicht explizit spezifiziert werden muss.
(Das ist Aufgabe der Implementierer.)
Siehe auch #141 

Es müssen nur die Datenquellen angegeben werden, die profileInstances (=KonfigParams) und ggf. forwardings,
aber keine eigenen Management-Services.
D.h. das neue Konzept wird stark vereinfacht.

Aktuelles Konzept:  
[MWDI device cache.pptx](https://github.com/openBackhaul/MicroWaveDeviceInventory/files/11421969/MWDI.device.cache.pptx)

---
*Old concept with own management services (deprecated)*

**MWDI**
Für das Management der DeviceList (und ElasticSearch-DB) müssen bestimmte Services vorhanden sein:
- **Initialisierung**: wenn das MWDI gestartet wird, muss einmalig die Liste der *connected* devices vom Controller abgerufen werden. Die gefundenen Devices müssen in die DeviceList geschrieben werden. 
- **Controller-Notifications**: das MWDI hat eine Subscription beim Controller, auf sich ändernde Device-Connection-Stati:
  1. von *connecting* nach *connected*: Device zur DeviceList hinzufügen
  2. von *connected* nach *connecting*: Device aus DeviceList löschen, Control Construct aus ElasticSearch-DB löschen
  3. *connecting* nach *unable-to-connect*: irrelevant (Device in (2) schon gelöscht)
  4. Device vom Controller gelöscht: wie (2) 
  5. Neues Device am Controller gemountet: irrelevant, erst relevant wenn Statuswechsel aus (1) eintritt 
- **Retention**: es kann sein, dass ein Device zwar *connected* ist, aber das CC zwischendurch nicht neu abgerufen werden kann. Ggf. sollte das CC dann nach längerer Wartezeit (konfigurierbare Retention-Time!) gelöscht werden.
- **ControlConstruct-Requests**: das MWDI ruft die CCs vom Controller ab. Das erfolgt für mehrere Devices aus der DeviceList gleichzeitig (ggf. mit ein paar Sekunden Wartezeit, zwischen dem Starten der einzelnen Requests; beim Shell-Tool werden aktuell ~300 Worker gleichzeitig gestartet)

---
**HistoricalMicrowaveDeviceInventory (HMDI)** 
- das HMDI ruft seine CCs vom MWDI ab, seine DeviceList wird entweder auch auf Basis der Controller-Notifications verwaltet oder es hat stattdessen eine Subscription beim MWDI (zu klären).  
- im MWDI werden Devices und zugehörige CCs gelöscht, wenn ein Device in *connecting* wechselt oder am Controller gelöscht wird. Im HMDI werden das Device & CC aber nicht gelöscht (ggf. aber wenn zwischendurch kein Update für das Device mehr erfolgt, aber nach einer bestimmten Retention)

---
**Latest version of concept**
[MWDI device cache_old_concept_with_own_mgmt_services.pptx](https://github.com/openBackhaul/MicroWaveDeviceInventory/files/11406607/MWDI.device.cache_old_concept_with_own_mgmt_services.pptx)

---
**Slides with ideas from Martin**
[odl-cache-design-proposals.pdf](https://github.com/openBackhaul/MicroWaveDeviceInventory/files/11135750/odl-cache-design-proposals.pdf)

**Comment by kmohr-soprasteria** [comment]
![image](https://user-images.githubusercontent.com/57349523/223414126-24db1360-8fb0-47e4-8cfa-9de296b1b00b.png)
![image](https://user-images.githubusercontent.com/57349523/223414171-1c44d866-48fc-438a-94e3-4723f040aa43.png)

**Comment by MartinSunal** [comment]
Attaching presented slide deck with potential ideas
[odl-cache-design-proposals.pdf](https://github.com/openBackhaul/MicroWaveDeviceInventory/files/11135750/odl-cache-design-proposals.pdf)
