### ISSUE TITLE
observing error 404 when MWDI is receiving device-attribute-value-change notification

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#910]
When MWDI started to receive the backup related device-attribute-value-change notification on API : v1/regard-device-attribute-value-change, observing error 404 
```
{"notification-proxy-1-0:attribute-value-changed-notification":{"counter":312,"timestamp":"2024-03-22T09:28:52+01:00","object-path":"/core-model-1-4:network-control-domain=live/control-construct=513559991B/backup-and-restore-1-0:backup-and-restore-pac/backup-and-restore-status","attribute-name":"backup-operation-status","new-value":"BACKUP_STATUS_TYPE_COMPLETED"}}

```

**Comment by nardecchia-siae** [comment]
The object-path does not exists in the list of available API's for MWDI, this is why the response is a 404 - not found

**Comment by Ziabatcha** [comment]
Backup and restore - avc notification not on priority .
Hence closing the issue.
