### ISSUE TITLE
Observing 500 internal server error when user give null value as input to POST parallel request 

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#921]
Below API is executed with null value, observing 500 internal server error. 

API:/v1/provide-list-of-parallel-links
Body:
{
  "link-id": ""
} 
Response:
{
  "code": 500,
  "message": "Internal Server Error"
}

**Comment by nardecchia-siae** [comment]
tested ok 1.1.2.c_impl

<img width="632" alt="image" src="https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/142794948/b5dfe4b6-f6b8-4a18-bd6f-206a6363da24">

**Comment by Ziabatcha** [comment]
Tested okay with 1.1.2d.
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/150062735/3ae866d0-f051-49f9-94bb-dd924fc48bb3)
