### ISSUE TITLE
Cache response is different from live response when field filter is having invalid value

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#924]
When live response is retrieved with invalid filter, observing 400 bad request code. 
But same request is executed for cache, observing response code as 200. 

```
curl -X GET "/core-model-1-4:network-control-domain=live/control-construct=CO17694/logical-termination-point=LTP-MWPS-TTP-3-1/layer-protocol=LP-MWPS-TTP-3-1/air-interface-2-0:air-interface-pac/air-interface-configuration?fields=%5C%5C" -H "accept: application/json" 
{
  "code": 400,
  "message": "Bad Request"
}
```
Cache response:
```
curl -X GET "/core-model-1-4:network-control-domain=cache/control-construc=CO17694/logical-termination-point=LTP-MWPS-TTP-3-1/layer-protocol=LP-MWPS-TTP-3-1/air-interface-2-0:air-interface-pac/air-interface-configuration?fields=%5C%5C" -H "accept: application/json"

{
  "air-interface-2-0:air-interface-configuration": {}
}
```

**Comment by Ziabatcha** [comment]
Issue still observed with latest package  MWDI 1.1.0.a_impl
Observing 500 Internal server error when tried to retrieve the config with invalid filter.

```
http://xx:xx/core-model-1-4:network-control-domain=cache/control-construct=CO17694/logical-termination-point=LTP-MWPS-TTP-3-1/layer-protocol=LP-MWPS-TTP-3-1/air-interface-2-0:air-interface-pac/air-interface-configuration?fields=aa

{
  "code": 500,
  "message": "Internal Server Error"
}

```

**Comment by nardecchia-siae** [comment]
Tested with version 1.1.2.d_impl

<img width="899" alt="image" src="https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/142794948/a5f1cacc-8f3a-4123-946b-3f8807565a8f">

**Comment by Ziabatcha** [comment]
Tested okay with 1.1.2d

![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/150062735/61a6ae0e-5b47-400b-bc30-923e6314a863)

![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/150062735/d6777cdb-1244-41b0-9de6-e0aa4f1c12f9)
