### ISSUE TITLE
Unable to find the updated device-list after realignment process 

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#933]
It would be helpful when MWDI showing the updated device-list after re-alignment process.
Also, if it is showing for deleted device list, new devices planning to add list in log, it would be better.

**Comment by kmohr-soprasteria** [comment]
Looks good to me. Maybe for debugging purposes we can also keep older versions of the file (configurable). Just like with logfiles like logfile.1, logfile.2 etc.; but that would depend on if this would be useful for TechM.

As for the files getting lost when the docker container is destroyed... if I remember correctly, it's possible to configure file locations outside the docker container, we the files could be written to. So we could go with that approach.

**Comment by zaia-siae** [comment]
We provided MWDI a new feature that each time the realignment event occurs
creates a new log file named as:

date_time.log   (for example: 2024.05.06_13.20.19.log)

The log file prints both the device list and the sliding window before and
after the realignment event. In addition both the added and the dropped 
elements are listed.

All these files are saved to the "realignment_logs" external volume. 
The procedure checks for the volume before saving the log file. If the 
volume doesn't exist the procedure doesn't save any file.

Following the options to add to docker run command for mapping the volume
that must be created with:

docker run --mount source=realignment_logs,target=/realignment_logs

The above command mounts the volume on the root of the container.

**Comment by Ziabatcha** [comment]
Tested okay with 1.1.2d.
Re-aligment logs are collected in docker path /var/lib/docker/volumes/realignment_logs/_data

![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/150062735/c5568144-e5cc-4d64-87cd-8b554d62bbc8)
[realignment_logs.txt](https://github.com/openBackhaul/MicroWaveDeviceInventory/files/15400590/realignment_logs.txt)
