### ISSUE TITLE
[ConvenienceService][Data] /v1/provide-list-of-device-interfaces: response headers missing

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#945]
In the tests to check for the life-cycle-state I call the service without a valid requestBody. In that case the service returns an error code + message, as it should.

But: In the responseBody I see that some headers are missing.
---  

**In another successful request I saw those marked headers:**  
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/ebbaf345-bb4b-427d-803a-6f828b08ae65)

---  
**The are missing in the tested service response:**
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/b4c55120-e308-498b-8bcc-f247c818840c)

From the specification:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/a6a3c181-a800-465c-82ef-f2cc3dc08ace)

**Comment by nardecchia-siae** [comment]
In case you use a wrong body message as in your testcase, the framework validator blocks the request before it can reach the implemented services.
The issue should be related not to the application but to the framework validator.

**Comment by kmohr-soprasteria** [comment]
@Prathiba/Iswaryaa: do we need to open an issue in AppPattern repository for that?

**Comment by kmohr-soprasteria** [comment]
Feedback from Iswaryaa:

> I checked the git repositories. I could not find the exact issue. But I could find a similar issue https://github.com/openBackhaul/ApplicationPattern/issues/663#issuecomment-1527150191. 
> 
> Also, as per OAS of services, the response headers are expected only for 200/204(positive) response-code, but not for negative response-codes. 
![image](https://github.com/user-attachments/assets/3868be96-b5cc-4bd2-b49d-816e45573294)

_IMO, also as per Prathiba's comment, unless we are having a business impact, it would be fine for not having the response-headers for negative responses. Thank you._
