### ISSUE TITLE
[ConvenienceService][Data] /v1/provide-list-of-device-interfaces needs to return all attributes marked as required

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#953]
See #952 for more detailed description. The same goes for this service.

Short summary:
- the service must return all attributes marked as required
- if an attribute is missing in the Cache, the attribute currently is just omitted from the responseBody
- instead of omitting such an attribute, it shall be returned with value = empty string

- if SIAE would require an OAS update, this would be done with v1.1.3 spec

(I did not check yet, if the service is omitting stuff if not found in the CC, but as the other service from #952 does that, I assume this service does it as well.)

**Comment by Ziabatcha** [comment]
Tested with latest  MWDI version 1.1.2.g_impl, Issue is no longer observed.
````
http://172.28.127.10:3008/v1/provide-list-of-device-interfaces

{
  "logical-termination-point-list": [
    {
      "uuid": "LTP-ETC-TTP-LAN-1-XG-SFP",
      "local-id": "LP-ETC-TTP-LAN-1-XG-SFP",
      "layer-protocol-name": "ethernet-container-2-0:LAYER_PROTOCOL_NAME_TYPE_ETHERNET_CONTAINER_LAYER"
    },
  `````
