### ISSUE TITLE
/v1/provide-list-of-actual-device-equipment: wrong error response (message) for unknown mount-name

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#954]
Same problem as #944
- The message goes like "unable to fetch records for LINK ..."
- should refer to the mountName instead of link

**Comment by nardecchia-siae** [comment]
Tested ok 1.1.2.c_impl

<img width="625" alt="image" src="https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/142794948/bb60faf7-96c9-4326-8b85-bc6212327ff3">
