### ISSUE TITLE
[ConvenienceService] Observing error "404" for API:/v1/provide-list-of-connected-devices

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#964]
When new version of MWDI is deployed (v1.1.2.b_impl), observing error 404 as shown below

```
Error message:
{
  "code": 404,
  "message": "Device list not found"
}

```
Docker logs:
```
[08.05.2024 06:53.40.064] [LOG]   Device list in Elasticsearch not found
[08.05.2024 06:53.40.099] [LOG]   traceIndicator: 1.1.1.1.1.1
[08.05.2024 06:53.40.166] [LOG]

```

**Comment by nardecchia-siae** [comment]
The problem was related to a wrong tag generation from github.
We have deleted the 1.1.2.b_impl tag, and we have created the same tag name with the latest commit, but for some reasons, it creates the tag with the old commit.

Now we have created a new tag 1.1.2.c_impl which contains the correct fix.

**Comment by nardecchia-siae** [comment]
Already fixed

**Comment by Ziabatcha** [comment]
Tested with latest  MWDI version 1.1.2.g_impl, Issue is no longer observed 

curl -X POST "http://XXXXX:XXXX/v1/provide-list-of-connected-devices" -H "accept: application/json" -H "user: User Name" -H "originator: Resolver" -H "x-correlator: 550e8400-e29b-11d4-a716-446655440000" -H "trace-indicator: 1.3.1" -H "customer-journey: Unknown value" -H "operation-key: Operation key not yet provided."


http://XXXX:XXX/v1/provide-list-of-connected-devices

![Connected-list](https://github.com/user-attachments/assets/ee99b9da-3f03-4927-8f51-aaf953b703bb)
