### ISSUE TITLE
/core-model-1-4:network-control-domain=cache/link={uuid} DELETE error response needs to be changed

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#968]
With a **GET** the service returns the following for an unknown link:
- responseCode: 404
- responseMessage: "unable to fetch records for link ..."
- i.e. FAIL

The **DELETE** returns:
- responseCode: 204
- responseMessage: {}
- i.e. success

The responseCode indicates a success, although actually nothing could be deleted, as the link is not found.
So I would have expected the responseCode to be 404.
The message should not be "unable to FETCH records for link ...", but "unable to DELETE records for link ..."

(The link-port service already returns a 404.)

**Comment by Ziabatcha** [comment]
```
Tested with latest package 1.1.2e, observing 500 Internal server error when trying to delete a link that doesnt exists.

http://xxxxx:3008/core-model-1-4:network-control-domain=cache/link=53361678

{
  "code": 500,
  "message": "Internal Server Error"
}

```

**Comment by kmohr-soprasteria** [comment]
SIAE info: next version will have 404.

**Comment by Ziabatcha** [comment]
Retested with package 1.1.2f and observing 404 response while trying to delete an unknown LINK . Hence closing the issue

http://xx:xx/core-model-1-4:network-control-domain=cache/link=LTP-MWPS-TTP-1-9

{
  "code": 404,
  "message": "unable to DELETE records for link LTP-MWPS-TTP-1-9"
}
