### ISSUE TITLE
/core-model-1-4:network-control-domain=cache/link={uuid}/link-port={uuid} - PUT for unknown link

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#970]
**Link-Port data can only be put if the related link is already inside the cache.**

For now it's okay, if we just allow linkports to be put, if the link is already there. (If we decide we want to be able to also put linkports if the link is not yet there, I think we can add that functionality still later on.)

But: **the responseMessage should at least indicate that the put failed, because the link is missing in the cache**.
So it should be something like "_link >linkId< not found in cache: cannot put linkport for unknown link_"

---
If I try the following put request I end up with a 500:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/2cb30dec-7a15-4eac-8ad7-907ca07a0f94)

However, if I put the link first:
- http://10.118.125.211:3008/core-model-1-4:network-control-domain=cache/link=link1
- responseCode: 204

and then try again, I get a 204:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/25eae53c-9b0f-420b-88ed-300e1594442b)

**Comment by Ziabatcha** [comment]
Tested with 1.1.2e and observed 404 response with message ("code": 404,
  "message": "link >533616788< not found in cache: cannot put linkport for unknown link" )

```
http://xxx:xxx/core-model-1-4:network-control-domain=cache/link=533616788/link-port=5

Body:
{
  "core-model-1-4:link-port": [
    {
      "local-id": "5",
      "link-port-direction": "core-model-1-4:PORT_DIRECTION_INPUT",
      "logical-termination-point": "513250008+2146435233"
    }
  ]
}
Response

{
  "code": 404,
  "message": "link >533616788< not found in cache: cannot put linkport for unknown link"
}

```

**Comment by Ziabatcha** [comment]
Tested with 1.1.2f and observed 404 response with message ("code": 404, "message": "link 533616788 not found in cache: cannot put linkport for unknown link"

Expected 404 response while trying to do the PUT for unknown link. its working as expected hence closing the issue

```
API: http://XX:XX/core-model-1-4:network-control-domain=cache/link=533616788/link-port=6
Body:
{
  "core-model-1-4:link-port": [
    {
      "local-id": "6",
      "link-port-direction": "core-model-1-4:PORT_DIRECTION_INPUT",
      "logical-termination-point": "513250008+2146435233"
    }
  ]
}

Response:
{
  "code": 404,
  "message": "link 533616788 not found in cache: cannot put linkport for unknown link"
}

```
