### ISSUE TITLE
[Data] UUID for Huawei equpment is incorrect - docker logs prints - Field not found: actual-equipment

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#973]
Huawei equipments:

```
Observing error prints for ACTUAL equipment in MWDI docker logs continuously. 
instead of UUID CO02050+AIR-EQUIPMENT-3-1 , the prints are going for CO02059+3-1 hence No element found error is observed in Docker logs.

```

[27.05.2024 06:17.12.879] [ERROR] NotFoundError: No elements found with UUID: CO02059+3-1
    at Object.exports.cacheResponseBuilder (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/cacheResponseBuilder.js:43:27)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:935:45
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[ERROR] NotFoundError: Field not found: actual-equipment
    at Object.exports.cacheResponseBuilder (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/cacheResponseBuilder.js:51:23)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:213:45
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[27.05.2024 06:17.11.904] [ERROR] NotFoundError: Field not found: actual-equipment

```
When we try the Actual equipment API to fetch the values for HUAWEI equipment its succuessful
http://XX:XXX/core-model-1-4:network-control-domain=cache/control-construct=XX/equipment=AIR-EQUIPMENT-3-1/actual-equipment

{
  "core-model-1-4:actual-equipment": {
    "local-id": "3-1",
    "lifecycle-state": "core-model-1-4:LIFECYCLE_STATE_INSTALLED",
    "operational-state": "core-model-1-4:OPERATIONAL_STATE_ENABLED",
    "physical-properties": {
      "temperature": "-1"
    },
```

```
http://xx:xx/core-model-1-4:network-control-domain=cache/control-construct=xx/equipment=CO02059%2BAIR-EQUIPMENT-3-1/actual-equipment
	
{
  "core-model-1-4:actual-equipment": {
    "local-id": "3-1",
    "lifecycle-state": "core-model-1-4:LIFECYCLE_STATE_INSTALLED",
    "operational-state": "core-model-1-4:OPERATIONAL_STATE_ENABLED",
    "physical-properties": {
      "temperature": "-1"
    },

```

**Comment by nardecchia-siae** [comment]
Could you please explain how the test has been performed?
In my environment and using swagger I got the correct data without errors when actual equipment equipment api is called.

I used mount-name:  CO02059 and equipment uuid: AIR-EQUIPMENT-3-1.
Who is calling the actual equipment with equipment uuid 3-1?

**Comment by nardecchia-siae** [comment]
I'm closing this issue as won't fix as the test is not correctly executed.
The control construct for this Huawei equipment for the "equipment" part is:
"**equipment**": [
        {
          **"uuid": "AIR-EQUIPMENT-3-1",**
          "lifecycle-state": "core-model-1-4:LIFECYCLE_STATE_INSTALLED",
          "operational-state": "core-model-1-4:OPERATIONAL_STATE_ENABLED",
          "**actual-equipment**": {
            **"local-id": "3-1",**
            "lifecycle-state": "core-model-1-4:LIFECYCLE_STATE_INSTALLED",
            "operational-state": "core-model-1-4:OPERATIONAL_STATE_ENABLED",
            "physical-properties": {
              "temperature": "-1"
            },
            "manufactured-thing": {
              "equipment-type": {
                "version": "2048.32768",
                "equipment-augment-1-0:equipment-type-pac": {
                  "lct-label": "X233LA",
                  "outside-label": "Label at the equipment not yet defined."
                },
                "model-identifier": "X233LA",
                "description": "Outdoor Unit",
                "part-type-identifier": "215241388010F8000162",
                "type-name": "X233LA"
              },
              "equipment-instance": {
                "manufacture-date": "2015-08-22",
                "serial-number": "215241388010F8000162"
              },
              "manufacturer-properties": {
                "manufacturer-name": "Huawei",
                "manufacturer-identifier": "64F81C"
              }
            },
            ........

It is correct that CO02059+3-1 is not present because the correct for UUID equipment is AIR-EQUIPMENT-3-1

**Comment by Ziabatcha** [comment]
Issue is being monitored .

**Comment by Ziabatcha** [comment]
Have been monitored for quite sometime, we dont see it in recent build. Hence closing the issue.
