### ISSUE TITLE
[Discussion] Requirements from ALAP side

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#980]
- Ana will document what's needed from ALAP side
- this issue will be used to document, what's needed and what will be done about it

**Comment by anacabbar** [comment]
ALAP needs from MWDI:

* Connection-status information of the Mount Points known to the controller (i.e. connected, connecting, unable-to-connect...)
* Notifications of ControllerAttributeValueChanges (i.e. updates about the connected or disconnected devices)

**Comment by kmohr-soprasteria** [comment]
can be included in service proposed in #1015

**Comment by kmohr-soprasteria** [comment]
Ana to confirm whether it's sufficient for APTP to subscribe at NotificationProxy instead of MWDI offering also a notification.

**Comment by kmohr-soprasteria** [comment]
Ana confirmed that for APTP (ALAP) it's sufficient to subscribe to the NotificationProxy - so MWDI will not implement an additional notification service.

> Ich denke, für den ALAP wäre es ausreichend, die Notifications zu den ControllerAttributeValueChanges direkt vom NP zu erhalten.
